"""CME-Ratings-v1: v4.2 plus a dynamic opponent-adjusted team-strength prior.

The backbone remains exactly CME-v4.2.  This branch adds a final-logit path that
uses strictly pregame dynamic offense/defense team ratings generated by
`data/scripts/build_team_strength_ratings.py`.

The rating pathway is intentionally residual and interpretable:

    final_logit = v4.2_logit
                + rating_weight * (rating_margin_prior / rating_margin_scale)
                + bounded_rating_feature_residual(rating_features, prior, v4.2_logit)

If the rating prior is unhelpful, training can drive the learned rating weight
and residual toward zero, recovering the v4.2 behavior.
"""
from __future__ import annotations

import math
import sys
from dataclasses import dataclass
from pathlib import Path

import torch
import torch.nn as nn

PROJECT_ROOT = Path(__file__).resolve().parents[2]
V42_SCRIPTS = PROJECT_ROOT / "models_cme_v4_2" / "scripts"
sys.path.insert(0, str(V42_SCRIPTS))

from cme_v4_2_model import (  # noqa: E402
    CmeV42,
    CmeV42Config,
    total_loss as total_loss_v42,
)

THIS_SCRIPTS = Path(__file__).resolve().parent
sys.path.insert(0, str(THIS_SCRIPTS))
from cme_ratings_v1_common import K_RATING_FEATURES  # noqa: E402


def _zero_last_linear(seq: nn.Sequential) -> None:
    for module in reversed(list(seq.modules())):
        if isinstance(module, nn.Linear):
            nn.init.zeros_(module.weight)
            if module.bias is not None:
                nn.init.zeros_(module.bias)
            return


@dataclass
class CmeRatingsV1Config(CmeV42Config):
    rating_feature_dim: int = K_RATING_FEATURES
    rating_hidden: int = 32
    rating_dropout: float = 0.05
    max_rating_feature_residual: float = 0.20
    rating_margin_scale: float = 12.0
    init_rating_logit_weight: float = 0.10


class CmeRatingsV1(CmeV42):
    def __init__(self, cfg: CmeRatingsV1Config) -> None:
        super().__init__(cfg)
        self.rating_cfg = cfg
        in_dim = int(cfg.rating_feature_dim) + 2  # rating prior + current v4.2 logit
        self.rating_prior_head = nn.Sequential(
            nn.Linear(in_dim, cfg.rating_hidden),
            nn.GELU(),
            nn.Dropout(cfg.rating_dropout),
            nn.Linear(cfg.rating_hidden, cfg.rating_hidden),
            nn.GELU(),
            nn.Dropout(cfg.rating_dropout),
            nn.Linear(cfg.rating_hidden, 1),
        )
        _zero_last_linear(self.rating_prior_head)
        self.rating_logit_weight = nn.Parameter(
            torch.tensor(float(cfg.init_rating_logit_weight), dtype=torch.float32)
        )

    def forward(self, batch: dict) -> dict:
        out = super().forward(batch)
        v42_logit = out["win_logit"]
        B = v42_logit.shape[0]
        rating_margin_prior = batch.get("rating_margin_prior")
        if rating_margin_prior is None:
            rating_margin_prior = torch.zeros(B, device=v42_logit.device, dtype=v42_logit.dtype)
        else:
            rating_margin_prior = rating_margin_prior.to(v42_logit.dtype)
        rating_logit_prior = rating_margin_prior / max(float(self.rating_cfg.rating_margin_scale), 1e-6)

        rating_features = batch.get("rating_features")
        if rating_features is None:
            rating_features = torch.zeros(
                B, int(self.rating_cfg.rating_feature_dim),
                device=v42_logit.device, dtype=v42_logit.dtype,
            )
        elif rating_features.size(-1) == 0 and self.rating_cfg.rating_feature_dim > 0:
            rating_features = torch.zeros(
                B, int(self.rating_cfg.rating_feature_dim),
                device=v42_logit.device, dtype=v42_logit.dtype,
            )
        else:
            rating_features = rating_features.to(v42_logit.dtype)

        rating_head_features = torch.cat([
            rating_features,
            rating_logit_prior.unsqueeze(-1),
            v42_logit.unsqueeze(-1),
        ], dim=-1)
        raw_rating_feature_residual = self.rating_prior_head(rating_head_features).squeeze(-1)
        if self.rating_cfg.max_rating_feature_residual > 0.0:
            rating_feature_residual = (
                self.rating_cfg.max_rating_feature_residual
                * torch.tanh(raw_rating_feature_residual)
            )
        else:
            rating_feature_residual = torch.zeros_like(v42_logit)

        has_rating = batch.get("has_rating_prior")
        if has_rating is None:
            has_rating = torch.ones_like(v42_logit)
        else:
            has_rating = has_rating.to(v42_logit.dtype)
        rating_linear_adjustment = self.rating_logit_weight * rating_logit_prior * has_rating
        rating_feature_residual = rating_feature_residual * has_rating
        rating_logit_adjustment = rating_linear_adjustment + rating_feature_residual
        final_logit = v42_logit + rating_logit_adjustment

        out.update({
            "win_logit_v42": v42_logit,
            "win_logit": final_logit,
            "rating_margin_prior": rating_margin_prior,
            "rating_logit_prior": rating_logit_prior,
            "rating_linear_adjustment": rating_linear_adjustment,
            "raw_rating_feature_residual": raw_rating_feature_residual,
            "rating_feature_residual": rating_feature_residual,
            "rating_logit_adjustment": rating_logit_adjustment,
            "rating_logit_weight": self.rating_logit_weight,
            "has_rating_prior": has_rating,
        })
        return out


def rating_feature_residual_l2_loss(out: dict) -> torch.Tensor:
    return out["rating_feature_residual"].pow(2).mean()


def rating_weight_l2_loss(out: dict) -> torch.Tensor:
    return out["rating_logit_weight"].pow(2)


def total_loss(
    out: dict,
    batch: dict,
    *,
    rating_feature_reg_w: float = 0.01,
    rating_weight_reg_w: float = 0.0005,
    **kwargs,
) -> tuple[torch.Tensor, dict]:
    base_total, diag = total_loss_v42(out, batch, **kwargs)
    L_rating_feature_reg = rating_feature_residual_l2_loss(out)
    L_rating_weight_reg = rating_weight_l2_loss(out)
    total = (
        base_total
        + rating_feature_reg_w * L_rating_feature_reg
        + rating_weight_reg_w * L_rating_weight_reg
    )
    diag = dict(diag)
    diag.update({
        "L_rating_feature_reg": L_rating_feature_reg.detach(),
        "L_rating_weight_reg": L_rating_weight_reg.detach(),
    })
    return total, diag


def _smoke() -> None:
    torch.manual_seed(0)
    cfg = CmeRatingsV1Config(
        vocab_size=64,
        num_teams=30,
        d=32,
        n_heads=4,
        n_self_layers=1,
        n_cross_layers=1,
        tabular_dim=4,
        team_emb_dim=8,
        player_stat_dim=0,
        rating_feature_dim=K_RATING_FEATURES,
    )
    model = CmeRatingsV1(cfg)
    B, Lh, La = 3, 8, 9
    batch = {
        "home_idx": torch.randint(1, cfg.vocab_size + 1, (B, Lh)),
        "away_idx": torch.randint(1, cfg.vocab_size + 1, (B, La)),
        "home_prob": torch.rand(B, Lh),
        "away_prob": torch.rand(B, La),
        "home_mask": torch.ones(B, Lh, dtype=torch.bool),
        "away_mask": torch.ones(B, La, dtype=torch.bool),
        "home_stats": torch.zeros(B, Lh, 0),
        "away_stats": torch.zeros(B, La, 0),
        "home_team_idx": torch.randint(1, cfg.num_teams + 1, (B,)),
        "away_team_idx": torch.randint(1, cfg.num_teams + 1, (B,)),
        "home_rest": torch.rand(B),
        "away_rest": torch.rand(B),
        "tabular": torch.randn(B, cfg.tabular_dim),
        "season_phase": torch.randn(B, 3).clamp(-1.0, 1.0),
        "label": torch.randint(0, 2, (B,), dtype=torch.float32),
        "margin": torch.randn(B),
        "team_box_home": torch.rand(B, 14),
        "team_box_away": torch.rand(B, 14),
        "sup_pair_game": torch.zeros(0, dtype=torch.long),
        "sup_pair_side": torch.zeros(0, dtype=torch.long),
        "sup_pair_off": torch.zeros(0, dtype=torch.long),
        "sup_pair_def": torch.zeros(0, dtype=torch.long),
        "sup_pair_y": torch.zeros(0, 9),
        "sup_pl_game": torch.zeros(0, dtype=torch.long),
        "sup_pl_side": torch.zeros(0, dtype=torch.long),
        "sup_pl_slot": torch.zeros(0, dtype=torch.long),
        "sup_pl_y": torch.zeros(0, 14),
        "home_alpha_off_actual": torch.softmax(torch.randn(B, Lh), dim=-1),
        "home_alpha_def_actual": torch.softmax(torch.randn(B, Lh), dim=-1),
        "away_alpha_off_actual": torch.softmax(torch.randn(B, La), dim=-1),
        "away_alpha_def_actual": torch.softmax(torch.randn(B, La), dim=-1),
        "home_off_exposure_valid": torch.ones(B),
        "away_off_exposure_valid": torch.ones(B),
        "rating_features": torch.randn(B, K_RATING_FEATURES),
        "rating_margin_prior": torch.randn(B) * 6.0,
        "has_rating_prior": torch.ones(B),
    }
    out = model(batch)
    loss, diag = total_loss(
        out,
        batch,
        box_weights=torch.ones(14),
        pair_weights=torch.ones(9),
    )
    loss.backward()
    print("[smoke] win_logit", out["win_logit"].shape)
    print("[smoke] rating_adjustment", out["rating_logit_adjustment"].shape)
    print("[smoke] loss", float(loss.item()))
    print("[smoke] L_rating_feature_reg", float(diag["L_rating_feature_reg"].item()))


if __name__ == "__main__":
    _smoke()
